# Generated by Django 3.2.1 on 2022-02-27 20:04

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('confirmation_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
            ],
        ),
    ]
