# Generated by Django 4.0.2 on 2022-02-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatest_beverage', '0003_customer_confirmation_id_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
